# Generated by Django 2.1.4 on 2018-12-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181218_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='readmore',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
